INSERT INTO CATEGORY(CATEGORYNAME) VALUES('Fashion');
INSERT INTO CATEGORY(CATEGORYNAME) VALUES('Electronics');
INSERT INTO CATEGORY(CATEGORYNAME) VALUES('Books');
INSERT INTO CATEGORY(CATEGORYNAME) VALUES('Groceries');
INSERT INTO CATEGORY(CATEGORYNAME) VALUES('Medicines');

INSERT INTO ROLE(`role`) VALUES('CONSUMER');
INSERT INTO ROLE(`role`) VALUES('SELLER');

INSERT INTO `USER`(username,password) VALUES('jack','pass_word');
INSERT INTO `USER`(username,password) VALUES('bob','pass_word');
INSERT INTO `USER`(username,password) VALUES('apple','pass_word');
INSERT INTO `USER`(username,password) VALUES('glaxo','pass_word');

INSERT INTO CART(TOTALAMOUNT,USERID) VALUES(20,1);
INSERT INTO CART(TOTALAMOUNT,USERID) VALUES(0,2);

INSERT INTO USER_ROLE(USER_USERID, ROLES_ROLEID) VALUES(1,1);
INSERT INTO USER_ROLE(USER_USERID, ROLES_ROLEID) VALUES(2,1);
INSERT INTO USER_ROLE(USER_USERID, ROLES_ROLEID) VALUES(3,2);
INSERT INTO USER_ROLE(USER_USERID, ROLES_ROLEID) VALUES(4,2);

INSERT INTO PRODUCT(price,PRODUCTNAME,CATEGORYID,USERID) VALUES(29190, 'Apple iPad 10.2 8th Gen WiFi iOS Tablet',2,3);

INSERT INTO PRODUCT(price,PRODUCTNAME,CATEGORYID,USERID) VALUES(10, 'Crocin pain relief tablet', 5, 4);


INSERT INTO CARTPRODUCT(CARTID,PRODUCTID,quantity) VALUES(1,2,2);


